import { LeadPriority, LeadSource, LeadStatus, PropertyListingStatus, PropertyTypeEnum } from "@prisma/client";

export const demoUser = {
  email: "demo@local.test",
  name: "Local Realtor Ops",
};

export const sampleLeads = [
  {
    firstName: "Maya",
    lastName: "Chen",
    email: "maya.chen@example.com",
    phone: "512-555-0134",
    source: LeadSource.REFERRAL,
    status: LeadStatus.QUALIFIED,
    priority: LeadPriority.HIGH,
    budgetMin: 475000,
    budgetMax: 625000,
    bedrooms: 3,
    bathrooms: 2,
    propertyType: "Single family",
    location: "North Austin",
    timeline: "1-3 months",
    notes: "Needs strong schools and a quiet street.",
  },
  {
    firstName: "Jordan",
    lastName: "Reed",
    email: "jordan.reed@example.com",
    phone: "737-555-0188",
    source: LeadSource.OPEN_HOUSE,
    status: LeadStatus.CONTACTED,
    priority: LeadPriority.MEDIUM,
    budgetMin: 350000,
    budgetMax: 430000,
    bedrooms: 2,
    bathrooms: 2,
    propertyType: "Townhome",
    location: "Round Rock",
    timeline: "3-6 months",
    notes: "Wants low maintenance and a short commute.",
  },
  {
    firstName: "Priya",
    lastName: "Nair",
    email: "priya.nair@example.com",
    phone: "512-555-0177",
    source: LeadSource.ZILLOW,
    status: LeadStatus.ACTIVE,
    priority: LeadPriority.URGENT,
    budgetMin: 700000,
    budgetMax: 850000,
    bedrooms: 4,
    bathrooms: 3,
    propertyType: "Single family",
    location: "Cedar Park",
    timeline: "Immediate",
    notes: "Relocating and ready to tour this week.",
  },
];

export const sampleProperties = [
  {
    address: "418 Redbud Trail",
    city: "Austin",
    state: "TX",
    zip: "78750",
    price: 589000,
    bedrooms: 3,
    bathrooms: 2.5,
    sqft: 2180,
    propertyType: PropertyTypeEnum.SINGLE_FAMILY,
    status: PropertyListingStatus.ACTIVE,
    description: "Updated home near trail access with a dedicated office.",
  },
  {
    address: "1128 Mesa View Drive",
    city: "Cedar Park",
    state: "TX",
    zip: "78613",
    price: 775000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3040,
    propertyType: PropertyTypeEnum.SINGLE_FAMILY,
    status: PropertyListingStatus.ACTIVE,
    description: "Large corner-lot home with flexible guest suite.",
  },
];
