'use client';
import { useEffect, useState } from 'react';
import { jsPDF } from 'jspdf';
import { FileSignature, Plus, X, Copy, Check, Download, Send, Trash2 } from 'lucide-react';
import SignaturePad from '@/components/SignaturePad';

type Signature = { id: string; signer: string; email: string; role: string; signedAt: string | null };
type Contract = {
  id: string;
  type: string;
  title: string;
  buyerName: string;
  buyerEmail: string;
  content: string;
  status: string;
  createdAt: string;
  signatures: Signature[];
};

const TYPE_LABELS: Record<string, string> = {
  BUYER_REPRESENTATION: 'Buyer Representation',
  SELLER_REPRESENTATION: 'Seller Listing',
  DUAL_AGENCY: 'Dual Agency Disclosure',
  COMMISSION_AGREEMENT: 'Commission Agreement',
  INSPECTION_WAIVER: 'Inspection Waiver',
  CONTINGENCY_REMOVAL: 'Contingency Removal',
  EARNEST_MONEY: 'Earnest Money Receipt',
  CUSTOM: 'Custom Agreement',
};

const STATUS_COLORS: Record<string, string> = {
  DRAFT: 'bg-gray-100 text-gray-800',
  SENT_FOR_SIGNATURE: 'bg-blue-100 text-blue-800',
  PARTIALLY_SIGNED: 'bg-amber-100 text-amber-800',
  SIGNED: 'bg-green-100 text-green-800',
  REJECTED: 'bg-red-100 text-red-800',
  EXPIRED: 'bg-red-100 text-red-800',
};

export default function ContractsPage() {
  const [contracts, setContracts] = useState<Contract[]>([]);
  const [loading, setLoading] = useState(true);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ type: 'BUYER_REPRESENTATION', buyerName: '', buyerEmail: '', propertyAddress: '', price: '', commissionRate: '3', termMonths: '6' });
  const [selected, setSelected] = useState<Contract | null>(null);
  const [agentSignature, setAgentSignature] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const load = async () => {
    setLoading(true);
    try {
      const res = await fetch('/api/contracts');
      const data = await res.json();
      if (data.ok) setContracts(data.contracts);
    } catch (e) { console.error(e); }
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault();
    await fetch('/api/contracts', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(form),
    });
    setShowForm(false);
    setForm({ type: 'BUYER_REPRESENTATION', buyerName: '', buyerEmail: '', propertyAddress: '', price: '', commissionRate: '3', termMonths: '6' });
    load();
  };

  const handleSend = async (contract: Contract) => {
    await fetch(`/api/contracts/${contract.id}`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ action: 'send', signatureData: agentSignature }),
    });
    setSelected(null);
    setAgentSignature(null);
    load();
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Delete this contract?')) return;
    await fetch(`/api/contracts/${id}`, { method: 'DELETE' });
    load();
  };

  const signLink = (id: string) => `${typeof window !== 'undefined' ? window.location.origin : ''}/sign/${id}`;

  const handleCopyLink = (id: string) => {
    navigator.clipboard.writeText(signLink(id));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadPdf = (contract: Contract) => {
    const doc = new jsPDF();
    const margin = 20;
    let y = 25;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(contract.title, margin, y);
    y += 12;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(contract.content, 170);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 15;

    contract.signatures.forEach((s) => {
      if (y > 260) { doc.addPage(); y = 25; }
      doc.setFont('helvetica', 'bold');
      doc.text(`Signed by ${s.signer} (${s.role})`, margin, y);
      doc.setFont('helvetica', 'normal');
      doc.text(s.signedAt ? new Date(s.signedAt).toLocaleString() : '', margin, y + 6);
      y += 15;
    });

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by The Realty App. Not a substitute for legal review.', margin, 288);
    doc.save(`${contract.title.replace(/[^a-z0-9]/gi, '-')}.pdf`);
  };

  if (loading) return <div className="p-6">Loading contracts...</div>;

  return (
    <div className="space-y-6 p-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2"><FileSignature className="text-indigo-600" /> Contracts &amp; E-Signature</h1>
          <p className="text-gray-500 mt-1">Create agreements, sign in person, or send a link for remote signing</p>
        </div>
        <button onClick={() => setShowForm(true)} className="inline-flex items-center gap-2 px-4 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">
          <Plus size={16} /> New Contract
        </button>
      </div>

      {showForm && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4" onClick={() => setShowForm(false)}>
          <div className="bg-white p-6 rounded-lg shadow-xl w-full max-w-lg" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold">New Contract</h2>
              <button onClick={() => setShowForm(false)} className="text-gray-400 hover:text-gray-600"><X size={20} /></button>
            </div>
            <form onSubmit={handleCreate} className="space-y-3">
              <div>
                <label className="block text-sm font-medium mb-1">Type</label>
                <select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} className="w-full px-3 py-2 border rounded-lg">
                  {Object.entries(TYPE_LABELS).map(([k, v]) => <option key={k} value={k}>{v}</option>)}
                </select>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div><label className="block text-sm font-medium mb-1">Buyer/Client Name</label><input required type="text" value={form.buyerName} onChange={e => setForm({ ...form, buyerName: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /></div>
                <div><label className="block text-sm font-medium mb-1">Email</label><input required type="email" value={form.buyerEmail} onChange={e => setForm({ ...form, buyerEmail: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /></div>
              </div>
              <div><label className="block text-sm font-medium mb-1">Property Address (optional)</label><input type="text" value={form.propertyAddress} onChange={e => setForm({ ...form, propertyAddress: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /></div>
              <div className="grid grid-cols-3 gap-3">
                <div><label className="block text-sm font-medium mb-1">Price ($)</label><input type="number" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /></div>
                <div><label className="block text-sm font-medium mb-1">Commission %</label><input type="number" step="0.1" value={form.commissionRate} onChange={e => setForm({ ...form, commissionRate: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /></div>
                <div><label className="block text-sm font-medium mb-1">Term (months)</label><input type="number" value={form.termMonths} onChange={e => setForm({ ...form, termMonths: e.target.value })} className="w-full px-3 py-2 border rounded-lg" /></div>
              </div>
              <button type="submit" className="w-full py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">Create Contract</button>
            </form>
          </div>
        </div>
      )}

      {selected && (
        <div className="fixed inset-0 bg-black/40 flex items-center justify-center z-50 p-4" onClick={() => { setSelected(null); setAgentSignature(null); }}>
          <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto" onClick={e => e.stopPropagation()}>
            <div className="p-6 border-b flex items-center justify-between sticky top-0 bg-white">
              <h2 className="text-lg font-semibold">{selected.title}</h2>
              <button onClick={() => { setSelected(null); setAgentSignature(null); }} className="text-gray-400 hover:text-gray-600"><X size={20} /></button>
            </div>
            <div className="p-6 whitespace-pre-wrap text-sm text-gray-700 font-mono bg-gray-50 border-b max-h-64 overflow-y-auto">{selected.content}</div>
            <div className="p-6 space-y-4">
              {selected.status === 'DRAFT' && (
                <>
                  <div>
                    <label className="block text-sm font-medium mb-1">Your Signature (agent)</label>
                    <SignaturePad onChange={setAgentSignature} />
                  </div>
                  <button onClick={() => handleSend(selected)} className="w-full py-2.5 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700 inline-flex items-center justify-center gap-2">
                    <Send size={16} /> Sign & Send for Buyer Signature
                  </button>
                </>
              )}

              {selected.status !== 'DRAFT' && (
                <div>
                  <p className="text-sm font-medium mb-2">Buyer signing link:</p>
                  <div className="flex gap-2">
                    <input readOnly value={signLink(selected.id)} className="flex-1 px-3 py-2 border rounded-lg text-sm bg-gray-50" />
                    <button onClick={() => handleCopyLink(selected.id)} className="px-3 py-2 bg-gray-100 rounded-lg hover:bg-gray-200">
                      {copied ? <Check size={16} className="text-green-600" /> : <Copy size={16} />}
                    </button>
                  </div>
                  <p className="text-xs text-gray-400 mt-2">Share this link by text or email — the buyer doesn&apos;t need an account to sign.</p>
                </div>
              )}

              <div>
                <p className="text-sm font-medium mb-2">Signatures collected:</p>
                {selected.signatures.length === 0 ? (
                  <p className="text-sm text-gray-400">None yet</p>
                ) : (
                  <ul className="text-sm space-y-1">
                    {selected.signatures.map(s => (
                      <li key={s.id} className="flex items-center gap-2 text-gray-600">
                        <Check size={14} className="text-green-500" /> {s.signer} ({s.role}) — {s.signedAt ? new Date(s.signedAt).toLocaleString() : 'pending'}
                      </li>
                    ))}
                  </ul>
                )}
              </div>

              {selected.status === 'SIGNED' && (
                <button onClick={() => downloadPdf(selected)} className="w-full py-2.5 bg-green-600 text-white rounded-lg hover:bg-green-700 inline-flex items-center justify-center gap-2">
                  <Download size={16} /> Download Signed PDF
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      {contracts.length === 0 ? (
        <div className="text-center py-12 text-gray-500">No contracts yet. Create one to get started.</div>
      ) : (
        <div className="bg-white rounded-lg shadow border overflow-hidden">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b bg-gray-50">
                <th className="text-left px-4 py-3 font-medium">Title</th>
                <th className="text-left px-4 py-3 font-medium">Type</th>
                <th className="text-left px-4 py-3 font-medium">Buyer/Client</th>
                <th className="text-left px-4 py-3 font-medium">Status</th>
                <th className="px-4 py-3"></th>
              </tr>
            </thead>
            <tbody className="divide-y">
              {contracts.map(c => (
                <tr key={c.id} className="hover:bg-gray-50 cursor-pointer" onClick={() => setSelected(c)}>
                  <td className="px-4 py-3 font-medium">{c.title}</td>
                  <td className="px-4 py-3">{TYPE_LABELS[c.type] || c.type}</td>
                  <td className="px-4 py-3">{c.buyerName}</td>
                  <td className="px-4 py-3"><span className={`px-2 py-0.5 text-xs rounded-full ${STATUS_COLORS[c.status]}`}>{c.status.replace(/_/g, ' ')}</span></td>
                  <td className="px-4 py-3 text-right">
                    <button onClick={(e) => { e.stopPropagation(); handleDelete(c.id); }} className="p-1 text-gray-400 hover:text-red-600"><Trash2 size={16} /></button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
}
